spring:
  application:
    name: hellosecurity

  # DB 연결정보 설정          
  datasource:
    url: jdbc:mariadb://localhost:3306/mydb?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:log4jdbc:mariadb://localhost:3306/mydb?serverTimezone=UTC&characterEncoding=UTF-8 # log4jdbc 사용시
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy # log4jdbc 사용시
    username: user1
    password: 1234    
    
  # JPA 설정    
  jpa:
    hibernate:
      ddl-auto: update  
    properties:
      hibernate:
        show_sql: true
        format_sql: true
