spring:
  application:
    name: hello-jsp-mariadb-mybatis-crud

  # JSP 설정  
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  # DB 연결정보 설정          
  datasource:
    url: jdbc:mariadb://localhost:3306/mydb?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:log4jdbc:mariadb://localhost:3306/mydb?serverTimezone=UTC&characterEncoding=UTF-8 # log4jdbc 사용시
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy # log4jdbc 사용시
    username: user1
    password: 1234
    
# mybatis 설정
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: mybatis/mappers/**/*.xml
  
logging:
  level:
    org:
      springframework:
        web:
          servlet:
            mvc:
              method:
                annotation: TRACE  
                